export const localData = {
  "metro": {
    "1": {
      image: "https://metrocouncil.org/getattachment/338f687a-c990-44e5-80ad-897443f259da/District-1-Judy-Johnson.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-1-Judy-Johnson.aspx"
    },
    "2": {
      image: "https://metrocouncil.org/getattachment/aa1973dc-e52a-4813-8685-65372d390ceb/District-2-Reva-Chamblis.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-2-Reva-Chamblis.aspx"
    },
    "3": {
      image: "https://metrocouncil.org/getattachment/b06df427-8559-433e-9419-ed9a8831d61c/District-3-Tyronne-Carter.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-3-Tyronne-Carter.aspx"
    },
    "4": {
      image: "https://metrocouncil.org/getattachment/c062402f-f23c-4b07-9b03-586c9c5ba98f/District-4-Deb-Barber.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-4-Deb-Barber.aspx"
    },
    "5": {
      image: "https://metrocouncil.org/getattachment/bd3b8ba2-60cf-4385-b8cb-9d7b3b00c877/District-5-John-Pacheco.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-5-John-Pacheco.aspx"
    },
    "6": {
      image: "https://metrocouncil.org/getattachment/590a04c5-eec2-4d8f-b952-d8f8d4bbef9d/District-6-Robert-Lilligren.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-6-Robert-Lilligren.aspx"
    },
    "7": {
      image: "https://metrocouncil.org/getattachment/7733c962-c1bb-4dd7-8ac8-eba2450e9542/District-7-Yassin-Osman.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-7-Yassin-Osman.aspx"
    },
    "8": {
      image: "https://metrocouncil.org/getattachment/2a9b6a5e-a70d-4708-86f0-ee8e6da2e3d1/District-8-Anjuli-Cameron.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-8-Anjuli-Cameron.aspx"
    },
    "9": {
      image: "https://metrocouncil.org/getattachment/759f0b05-d1d2-4a7f-838a-5e7e39910d1e/District-9-Diego-Morales.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-9-Diego-Morales.aspx"
    },
    "10": {
      image: "https://metrocouncil.org/getattachment/23e103c3-f49a-46f3-8776-cfe190d1afb4/District-10-Peter-Lindstrom.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-10-Peter-Lindstrom.aspx"
    },
    "11": {
      image: "https://metrocouncil.org/getattachment/966ee9a7-0a0e-421b-8b67-e5d4d98c0271/District-11-Gail-Cederberg.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-11-Gail-Cederberg.aspx"
    },
    "12": {
      image: "https://metrocouncil.org/getattachment/3807b7a9-0c71-4ba9-817e-48eed3e7c965/District-12-Susan-Vento.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-12-Susan-Vento.aspx"
    },
    "13": {
      image: "https://metrocouncil.org/getattachment/5da74567-82a9-447d-8301-06c379ea7c7e/District-13-Chai-Lee.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-13-Chai-Lee.aspx"
    },
    "14": {
      image: "https://metrocouncil.org/getattachment/13d74f67-6afb-4281-bd8b-8335bce5fc47/District-14-Toni-Carter.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-14-Toni-Carter.aspx"
    },
    "15": {
      image: "https://metrocouncil.org/getattachment/8eb7dedf-40f8-44fa-8551-fc806cec41b0/District-15-Tenzin-Dolkar.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-15-Tenzin-Dolkar.aspx"
    },
    "16": {
      image: "https://metrocouncil.org/getattachment/4117bcc5-33f0-47cf-9d97-89e0f32acb24/District-16-Wendy-Wulff.aspx",
      url: "https://metrocouncil.org/About-Us/Who-We-Are/CouncilMembers/District-16-Wendy-Wulff.aspx"
    }
  },
  "ward": {
    "1": {
      url:"https://www.stpaul.gov/department/city-council/ward-1"
    },
    "2": {
      url:"https://www.stpaul.gov/department/city-council/ward-2"
    },
    "3": {
      url:"https://www.stpaul.gov/department/city-council/ward-3"
    },
    "4": {
      url:"https://www.stpaul.gov/department/city-council/ward-4"
    },
    "5": {
      url:"https://www.stpaul.gov/department/city-council/ward-5"
    },
    "6": {
      url:"https://www.stpaul.gov/department/city-council/ward-6"
    },
    "7": {
      url:"https://www.stpaul.gov/department/city-council/ward-7"
    }
  },
  "commissioner": {
    "1":{
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/Frethem-WebCrop.jpg"
    },
    "2": {
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/MaryJoM-EwbCrop.jpg"
    },
    "3": {
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/Trista-MatasCastillo_WebCrop.jpg"
    },
    "4": {
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/RenaMoran-WebCrop_0.jpg"
    },
    "5": {
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/Ortega_WebCrop.jpg"
    },
    "6": {
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/MaiChongX-WebCrop_0.jpg"
    },
    "7": {
      image: "https://www.ramseycounty.us/sites/default/files/Government/Leadership/Board%20of%20Commissioners/VictoriaReinhard-WebCrop.jpg"
    }
  }
}

export const stateHouse = {
  "45B": {
    title: "Rep. Patty Acomb",
    name: "Patty Acomb",
    district: "45B",
    party: "DFL",
    address: "593 State Office Building St. Paul, MN 55155",
    phone: "651-296-9934",
    email: "rep.patty.acomb@house.mn.gov",
  },
  "59B": {
    title: "Rep. Esther Agbaje",
    name: "Esther Agbaje",
    district: "59B",
    party: "DFL",
    address: "437 State Office Building St. Paul, MN 55155",
    phone: "651-296-8659",
    email: "rep.esther.agbaje@house.mn.gov",
  },
  "20A": {
    title: "Rep. Pam Altendorf",
    name: "Pam Altendorf",
    district: "20A",
    party: "R",
    address: "331 State Office Building St. Paul, MN 55155",
    phone: "651-296-8635",
    email: "rep.pam.altendorf@house.mn.gov",
  },
  "33A": {
    title: "Rep. Patti Anderson",
    name: "Patti Anderson",
    district: "33A",
    party: "R",
    address: "387 State Office Building St. Paul, MN 55155",
    phone: "651-296-3018",
    email: "rep.patti.anderson@house.mn.gov",
  },
  "12A": {
    title: "Rep. Paul Anderson",
    name: "Paul Anderson",
    district: "12A",
    party: "R",
    address: "277 State Office Building St. Paul, MN 55155",
    phone: "651-296-4317",
    email: "rep.paul.anderson@house.mn.gov",
  },
  "09A": {
    title: "Rep. Jeff Backer",
    name: "Jeff Backer",
    district: "09A",
    party: "R",
    address: "369 State Office Building St. Paul, MN 55155",
    phone: "651-296-4929",
    email: "rep.jeff.backer@house.mn.gov",
  },
  "37B": {
    title: "Rep. Kristin Bahner",
    name: "Kristin Bahner",
    district: "37B",
    party: "DFL",
    address: "525 State Office Building St. Paul, MN 55155",
    phone: "651-296-5502",
    email: "rep.kristin.bahner@house.mn.gov",
  },
  "54B": {
    title: "Rep. Ben Bakeberg",
    name: "Ben Bakeberg",
    district: "54B",
    party: "R",
    address: "329 State Office Building St. Paul, MN 55155",
    phone: "651-296-5185",
    email: "rep.ben.bakeberg@house.mn.gov",
  },
  "16B": {
    title: "Rep. Dave Baker",
    name: "Dave Baker",
    district: "16B",
    party: "R",
    address: "259 State Office Building St. Paul, MN 55155",
    phone: "651-296-6206",
    email: "rep.dave.baker@house.mn.gov",
  },
  "40B": {
    title: "Rep. Jamie Becker-Finn",
    name: "Jamie Becker-Finn",
    district: "40B",
    party: "DFL",
    address: "559 State Office Building St. Paul, MN 55155",
    phone: "651-296-7153",
    email: "rep.jamie.becker-finn@house.mn.gov",
  },
  "23A": {
    title: "Rep. Peggy Bennett",
    name: "Peggy Bennett",
    district: "23A",
    party: "R",
    address: "307 State Office Building St. Paul, MN 55155",
    phone: "651-296-8216",
    email: "rep.peggy.bennett@house.mn.gov",
  },
  "55B": {
    title: "Rep. Kaela Berg",
    name: "Kaela Berg",
    district: "55B",
    party: "DFL",
    address: "577 State Office Building St. Paul, MN 55155",
    phone: "651-296-5387",
    email: "rep.kaela.berg@house.mn.gov",
  },
  "56A": {
    title: "Rep. Robert Bierman",
    name: "Robert Bierman",
    district: "56A",
    party: "DFL",
    address: "579 State Office Building St. Paul, MN 55155",
    phone: "651-296-5506",
    email: "rep.robert.bierman@house.mn.gov",
  },
  "02B": {
    title: "Rep. Matt Bliss",
    name: "Matt Bliss",
    district: "02B",
    party: "R",
    address: "311 State Office Building St. Paul, MN 55155",
    phone: "651-296-5516",
    email: "rep.matt.bliss@house.mn.gov",
  },
  "18A": {
    title: "Rep. Jeff Brand",
    name: "Jeff Brand",
    district: "18A",
    party: "DFL",
    address: "501 State Office Building St. Paul, MN 55155",
    phone: "651-296-8634",
    email: "rep.jeff.brand@house.mn.gov",
  },
  "01A": {
    title: "Rep. John Burkel",
    name: "John Burkel",
    district: "01A",
    party: "R",
    address: "309 State Office Building St. Paul, MN 55155",
    phone: "651-296-9635",
    email: "rep.john.burkel@house.mn.gov",
  },
  "42A": {
    title: "Rep. Ned Carroll",
    name: "Ned Carroll",
    district: "42A",
    party: "DFL",
    address: "565 State Office Building St. Paul, MN 55155",
    phone: "651-296-5510",
    email: "rep.ned.carroll@house.mn.gov",
  },
  "47B": {
    title: "Rep. Ethan Cha",
    name: "Ethan Cha",
    district: "47B",
    party: "DFL",
    address: "527 State Office Building St. Paul, MN 55155",
    phone: "651-296-1147",
    email: "rep.ethan.cha@house.mn.gov",
  },
  "53A": {
    title: "Rep. Mary Frances Clardy",
    name: "Mary Frances Clardy",
    district: "53A",
    party: "DFL",
    address: "529 State Office Building St. Paul, MN 55155",
    phone: "651-296-3533",
    email: "rep.mary.frances.clardy@house.mn.gov",
  },
  "51B": {
    title: "Rep. Nathan Coulter",
    name: "Nathan Coulter",
    district: "51B",
    party: "DFL",
    address: "569 State Office Building St. Paul, MN 55155",
    phone: "651-296-4218",
    email: "rep.nathan.coulter@house.mn.gov",
  },
  "36B": {
    title: "Rep. Brion Curran",
    name: "Brion Curran",
    district: "36B",
    party: "DFL",
    address: "531 State Office Building St. Paul, MN 55155",
    phone: "651-296-4342",
    email: "rep.brion.curran@house.mn.gov",
  },
  "19A": {
    title: "Rep. Brian Daniels",
    name: "Brian Daniels",
    district: "19A",
    party: "R",
    address: "231 State Office Building St. Paul, MN 55155",
    phone: "651-296-8237",
    email: "rep.brian.daniels@house.mn.gov",
  },
  "26B": {
    title: "Rep. Greg Davids",
    name: "Greg Davids",
    district: "26B",
    party: "R",
    address: "283 State Office Building St. Paul, MN 55155",
    phone: "651-296-9278",
    email: "rep.greg.davids@house.mn.gov",
  },
  "06A": {
    title: "Rep. Ben Davis",
    name: "Ben Davis",
    district: "06A",
    party: "R",
    address: "227 State Office Building St. Paul, MN 55155",
    phone: "651-296-0172",
    email: "rep.ben.davis@house.mn.gov",
  },
  "13A": {
    title: "Rep. Lisa Demuth",
    name: "Lisa Demuth",
    district: "13A",
    party: "R",
    address: "267 State Office Building St. Paul, MN 55155",
    phone: "651-296-4373",
    email: "rep.lisa.demuth@house.mn.gov",
  },
  "11A": {
    title: "Rep. Jeff Dotseth",
    name: "Jeff Dotseth",
    district: "11A",
    party: "R",
    address: "343 State Office Building St. Paul, MN 55155",
    phone: "651-296-4308",
    email: "rep.jeff.dotseth@house.mn.gov",
  },
  "50A": {
    title: "Rep. Heather Edelson",
    name: "Heather Edelson",
    district: "50A",
    party: "DFL",
    address: "549 State Office Building St. Paul, MN 55155",
    phone: "651-296-4363",
    email: "rep.heather.edelson@house.mn.gov",
  },
  "50B": {
    title: "Rep. Steve Elkins",
    name: "Steve Elkins",
    district: "50B",
    party: "DFL",
    address: "517 State Office Building St. Paul, MN 55155",
    phone: "651-296-7803",
    email: "rep.steve.elkins@house.mn.gov",
  },
  "36A": {
    title: "Rep. Elliott Engen",
    name: "Elliott Engen",
    district: "36A",
    party: "R",
    address: "345 State Office Building St. Paul, MN 55155",
    phone: "651-296-2365",
    email: "rep.elliott.engen@house.mn.gov",
  },
  "39B": {
    title: "Rep. Sandra Feist",
    name: "Sandra Feist",
    district: "39B",
    party: "DFL",
    address: "409 State Office Building St. Paul, MN 55155",
    phone: "651-296-4331",
    email: "rep.sandra.feist@house.mn.gov",
  },
  "66A": {
    title: "Rep. Leigh Finke",
    name: "Leigh Finke",
    district: "66A",
    party: "DFL",
    address: "423 State Office Building St. Paul, MN 55155",
    phone: "651-296-3824",
    email: ""
  },
  "44A": {
    title: "Rep. Peter Fischer",
    name: "Peter Fischer",
    district: "44A",
    party: "DFL",
    address: "551 State Office Building St. Paul, MN 55155",
    phone: "651-296-5363",
    email: "rep.peter.fischer@house.mn.gov",
  },
  "21B": {
    title: "Rep. Marj Fogelman",
    name: "Marj Fogelman",
    district: "21B",
    party: "R",
    address: "323 State Office Building St. Paul, MN 55155",
    phone: "651-296-5373",
    email: "rep.marj.fogelman@house.mn.gov",
  },
  "12B": {
    title: "Rep. Mary Franson",
    name: "Mary Franson",
    district: "12B",
    party: "R",
    address: "303 State Office Building St. Paul, MN 55155",
    phone: "651-296-3201",
    email: "rep.mary.franson@house.mn.gov",
  },
  "43A": {
    title: "Rep. Cedrick Frazier",
    name: "Cedrick Frazier",
    district: "43A",
    party: "DFL",
    address: "439 State Office Building St. Paul, MN 55155",
    phone: "651-296-4255",
    email: "rep.cedrick.frazier@house.mn.gov",
  },
  "18B": {
    title: "Rep. Luke Frederick",
    name: "Luke Frederick",
    district: "18B",
    party: "DFL",
    address: "487 State Office Building St. Paul, MN 55155",
    phone: "651-296-3248",
    email: "rep.luke.frederick@house.mn.gov",
  },
  "43B": {
    title: "Rep. Mike Freiberg",
    name: "Mike Freiberg",
    district: "43B",
    party: "DFL",
    address: "381 State Office Building St. Paul, MN 55155",
    phone: "651-296-4176",
    email: "rep.mike.freiberg@house.mn.gov",
  },
  "58B": {
    title: "Rep. Pat Garofalo",
    name: "Pat Garofalo",
    district: "58B",
    party: "R",
    address: "295 State Office Building St. Paul, MN 55155",
    phone: "651-296-1069",
    email: "rep.pat.garofalo@house.mn.gov",
  },
  "17A": {
    title: "Rep. Dawn Gillman",
    name: "Dawn Gillman",
    district: "17A",
    party: "R",
    address: "213 State Office Building St. Paul, MN 55155",
    phone: "651-296-4228",
    email: "rep.dawn.gillman@house.mn.gov",
  },
  "62A": {
    title: "Rep. Aisha Gomez",
    name: "Aisha Gomez",
    district: "62A",
    party: "DFL",
    address: "453 State Office Building St. Paul, MN 55155",
    phone: "651-296-7152",
    email: "rep.aisha.gomez@house.mn.gov",
  },
  "63B": {
    title: "Rep. Emma Greenman",
    name: "Emma Greenman",
    district: "63B",
    party: "DFL",
    address: "433 State Office Building St. Paul, MN 55155",
    phone: "651-296-4200",
    email: "rep.emma.greenman@house.mn.gov",
  },
  "02A": {
    title: "Rep. Matt Grossell",
    name: "Matt Grossell",
    district: "02A",
    party: "R",
    address: "371 State Office Building St. Paul, MN 55155",
    phone: "651-296-4265",
    email: "rep.matt.grossell@house.mn.gov",
  },
  "53B": {
    title: "Rep. Rick Hansen",
    name: "Rick Hansen",
    district: "53B",
    party: "DFL",
    address: "407 State Office Building St. Paul, MN 55155",
    phone: "651-296-6828",
    email: "rep.rick.hansen@house.mn.gov",
  },
  "55A": {
    title: "Rep. Jessica Hanson",
    name: "Jessica Hanson",
    district: "55A",
    party: "DFL",
    address: "421 State Office Building St. Paul, MN 55155",
    phone: "651-296-4212",
    email: "rep.jessica.hanson@house.mn.gov",
  },
  "17B": {
    title: "Rep. Bobbie Harder",
    name: "Bobbie Harder",
    district: "17B",
    party: "R",
    address: "211 State Office Building St. Paul, MN 55155",
    phone: "651-296-4229",
    email: "rep.bobbie.harder@house.mn.gov",
  },
  "62B": {
    title: "Rep. Hodan Hassan",
    name: "Hodan Hassan",
    district: "62B",
    party: "DFL",
    address: "597 State Office Building St. Paul, MN 55155",
    phone: "651-296-0294",
    email: "rep.hodan.hassan@house.mn.gov",
  },
  "06B": {
    title: "Rep. Josh Heintzeman",
    name: "Josh Heintzeman",
    district: "06B",
    party: "R",
    address: "375 State Office Building St. Paul, MN 55155",
    phone: "651-296-4333",
    email: "rep.josh.heintzeman@house.mn.gov",
  },
  "47A": {
    title: "Rep. Amanda Hemmingsen-Jaeger",
    name: "Amanda Hemmingsen-Jaeger",
    district: "47A",
    party: "DFL",
    address: "537 State Office Building St. Paul, MN 55155",
    phone: "651-296-7807",
    email: "rep.amanda.hemmingsen-jaeger@house.mn.gov",
  },
  "64A": {
    title: "Rep. Kaohly Vang Her",
    name: "Kaohly Vang Her",
    district: "64A",
    party: "DFL",
    address: "359 State Office Building St. Paul, MN 55155",
    phone: "651-296-8799",
    email: "rep.kaohly.her@house.mn.gov",
  },
  "25A": {
    title: "Rep. Kim Hicks",
    name: "Kim Hicks",
    district: "25A",
    party: "DFL",
    address: "413 State Office Building St. Paul, MN 55155",
    phone: "651-296-4378",
    email: "rep.kim.hicks@house.mn.gov",
  },
  "33B": {
    title: "Rep. Josiah Hill",
    name: "Josiah Hill",
    district: "33B",
    party: "DFL",
    address: "415 State Office Building St. Paul, MN 55155",
    phone: "651-296-4124",
    email: "rep.josiah.hill@house.mn.gov",
  },
  "66B": {
    title: "Rep. Athena Hollins",
    name: "Athena Hollins",
    district: "66B",
    party: "DFL",
    address: "471 State Office Building St. Paul, MN 55155",
    phone: "651-296-4224",
    email: "rep.athena.hollins@house.mn.gov",
  },
  "61A": {
    title: "Rep. Frank Hornstein",
    name: "Frank Hornstein",
    district: "61A",
    party: "DFL",
    address: "563 State Office Building St. Paul, MN 55155",
    phone: "651-296-9281",
    email: "rep.frank.hornstein@house.mn.gov",
  },
  "34B": {
    title: "Rep. Melissa Hortman",
    name: "Melissa Hortman",
    district: "34B",
    party: "DFL",
    address: "463 State Office Building St. Paul, MN 55155",
    phone: "651-296-4280",
    email: "rep.melissa.hortman@house.mn.gov",
  },
  "51A": {
    title: "Rep. Michael Howard",
    name: "Michael Howard",
    district: "51A",
    party: "DFL",
    address: "473 State Office Building St. Paul, MN 55155",
    phone: "651-296-7158",
    email: "rep.michael.howard@house.mn.gov",
  },
  "41B": {
    title: "Rep. Shane Hudella",
    name: "Shane Hudella",
    district: "41B",
    party: "R",
    address: "289 State Office Building St. Paul, MN 55155",
    phone: "651-296-3135",
    email: "rep.shane.hudella@house.mn.gov",
  },
  "30A": {
    title: "Rep. Walter Hudson",
    name: "Walter Hudson",
    district: "30A",
    party: "R",
    address: "317 State Office Building St. Paul, MN 55155",
    phone: "651-296-1534",
    email: "rep.walter.hudson@house.mn.gov",
  },
  "56B": {
    title: "Rep. John Huot",
    name: "John Huot",
    district: "56B",
    party: "DFL",
    address: "591 State Office Building St. Paul, MN 55155",
    phone: "651-296-4306",
    email: "rep.john.huot@house.mn.gov",
  },
  "65A": {
    title: "Rep. Samakab Hussein",
    name: "Samakab Hussein",
    district: "65A",
    party: "DFL",
    address: "521 State Office Building St. Paul, MN 55155",
    phone: "651-296-5158",
    email: "rep.samakab.hussein@house.mn.gov",
  },
  "07A": {
    title: "Rep. Spencer Igo",
    name: "Spencer Igo",
    district: "07A",
    party: "R",
    address: "233 State Office Building St. Paul, MN 55155",
    phone: "651-296-4936",
    email: "rep.spencer.igo@house.mn.gov",
  },
  "20B": {
    title: "Rep. Steven Jacob",
    name: "Steven Jacob",
    district: "20B",
    party: "R",
    address: "389 State Office Building St. Paul, MN 55155",
    phone: "651-296-2273",
    email: "rep.steven.jacob@house.mn.gov",
  },
  "28A": {
    title: "Rep. Brian Johnson",
    name: "Brian Johnson",
    district: "28A",
    party: "R",
    address: "243 State Office Building St. Paul, MN 55155",
    phone: "651-296-4346",
    email: "rep.brian.johnson@house.mn.gov",
  },
  "60A": {
    title: "Rep. Sydney Jordan",
    name: "Sydney Jordan",
    district: "60A",
    party: "DFL",
    address: "553 State Office Building St. Paul, MN 55155",
    phone: "651-296-4219",
    email: "rep.sydney.jordan@house.mn.gov",
  },
  "04B": {
    title: "Rep. Jim Joy",
    name: "Jim Joy",
    district: "04B",
    party: "R",
    address: "315 State Office Building St. Paul, MN 55155",
    phone: "651-296-6829",
    email: "rep.jim.joy@house.mn.gov",
  },
  "04A": {
    title: "Rep. Heather Keeler",
    name: "Heather Keeler",
    district: "04A",
    party: "DFL",
    address: "431 State Office Building St. Paul, MN 55155",
    phone: "651-296-5515",
    email: "rep.heather.keeler@house.mn.gov",
  },
  "01B": {
    title: "Rep. Debra Kiel",
    name: "Debra Kiel",
    district: "01B",
    party: "R",
    address: "203 State Office Building St. Paul, MN 55155",
    phone: "651-296-5091",
    email: "rep.deb.kiel@house.mn.gov",
  },
  "42B": {
    title: "Rep. Ginny Klevorn",
    name: "Ginny Klevorn",
    district: "42B",
    party: "DFL",
    address: "581 State Office Building St. Paul, MN 55155",
    phone: "651-296-5511",
    email: "rep.ginny.klevorn@house.mn.gov",
  },
  "05A": {
    title: "Rep. Krista Knudsen",
    name: "Krista Knudsen",
    district: "05A",
    party: "R",
    address: "225 State Office Building St. Paul, MN 55155",
    phone: "651-296-9918",
    email: "rep.krista.knudsen@house.mn.gov",
  },
  "39A": {
    title: "Rep. Erin Koegel",
    name: "Erin Koegel",
    district: "39A",
    party: "DFL",
    address: "445 State Office Building St. Paul, MN 55155",
    phone: "651-296-5369",
    email: "rep.erin.koegel@house.mn.gov",
  },
  "49B": {
    title: "Rep. Carlie Kotyza-Witthuhn",
    name: "Carlie Kotyza-Witthuhn",
    district: "49B",
    party: "DFL",
    address: "567 State Office Building St. Paul, MN 55155",
    phone: "651-296-7449",
    email: "rep.carlie.kotyza-witthuhn@house.mn.gov",
  },
  "08B": {
    title: "Rep. Alicia 'Liish' Kozlowski",
    name: "Alicia 'Liish' Kozlowski",
    district: "08B",
    party: "DFL",
    address: "429 State Office Building St. Paul, MN 55155",
    phone: "651-296-2228",
    email: "rep.alicia.kozlowski@house.mn.gov",
  },
  "57A": {
    title: "Rep. Jon Koznick",
    name: "Jon Koznick",
    district: "57A",
    party: "R",
    address: "281 State Office Building St. Paul, MN 55155",
    phone: "651-296-6926",
    email: "rep.jon.koznick@house.mn.gov",
  },
  "46A": {
    title: "Rep. Larry Kraft",
    name: "Larry Kraft",
    district: "46A",
    party: "DFL",
    address: "515 State Office Building St. Paul, MN 55155",
    phone: "651-296-7026",
    email: "rep.larry.kraft@house.mn.gov",
  },
  "10A": {
    title: "Rep. Ron Kresha",
    name: "Ron Kresha",
    district: "10A",
    party: "R",
    address: "207 State Office Building St. Paul, MN 55155",
    phone: "651-296-4247",
    email: "rep.ron.kresha@house.mn.gov",
  },
  "27B": {
    title: "Rep. Bryan Lawrence",
    name: "Bryan Lawrence",
    district: "27B",
    party: "R",
    address: "357 State Office Building St. Paul, MN 55155",
    phone: "651-296-5364",
    email: "rep.bryan.lawrence@house.mn.gov",
  },
  "59A": {
    title: "Rep. Fue Lee",
    name: "Fue Lee",
    district: "59A",
    party: "DFL",
    address: "485 State Office Building St. Paul, MN 55155",
    phone: "651-296-4262",
    email: "rep.fue.lee@house.mn.gov",
  },
  "67A": {
    title: "Rep. Liz Lee",
    name: "Liz Lee",
    district: "67A",
    party: "DFL",
    address: "539 State Office Building St. Paul, MN 55155",
    phone: "651-296-4277",
    email: ""
  },
  "24B": {
    title: "Rep. Tina Liebling",
    name: "Tina Liebling",
    district: "24B",
    party: "DFL",
    address: "477 State Office Building St. Paul, MN 55155",
    phone: "651-296-0573",
    email: "rep.tina.liebling@house.mn.gov",
  },
  "44B": {
    title: "Rep. Leon Lillie",
    name: "Leon Lillie",
    district: "44B",
    party: "DFL",
    address: "365 State Office Building St. Paul, MN 55155",
    phone: "651-296-1188",
    email: "rep.leon.lillie@house.mn.gov",
  },
  "07B": {
    title: "Rep. Dave Lislegard",
    name: "Dave Lislegard",
    district: "07B",
    party: "DFL",
    address: "451 State Office Building St. Paul, MN 55155",
    phone: "651-296-0170",
    email: "rep.dave.lislegard@house.mn.gov",
  },
  "61B": {
    title: "Rep. Jamie Long",
    name: "Jamie Long",
    district: "61B",
    party: "DFL",
    address: "459 State Office Building St. Paul, MN 55155",
    phone: "651-296-5375",
    email: "rep.jamie.long@house.mn.gov",
  },
  "29A": {
    title: "Rep. Joe McDonald",
    name: "Joe McDonald",
    district: "29A",
    party: "R",
    address: "241 State Office Building St. Paul, MN 55155",
    phone: "651-296-4336",
    email: "rep.joe.mcdonald@house.mn.gov",
  },
  "27A": {
    title: "Rep. Shane Mekeland",
    name: "Shane Mekeland",
    district: "27A",
    party: "R",
    address: "215 State Office Building St. Paul, MN 55155",
    phone: "651-296-2451",
    email: "rep.shane.mekeland@house.mn.gov",
  },
  "40A": {
    title: "Rep. Kelly Moller",
    name: "Kelly Moller",
    district: "40A",
    party: "DFL",
    address: "509 State Office Building St. Paul, MN 55155",
    phone: "651-296-0141",
    email: "rep.kelly.moller@house.mn.gov",
  },
  "23B": {
    title: "Rep. Patricia Mueller",
    name: "Patricia Mueller",
    district: "23B",
    party: "R",
    address: "253 State Office Building St. Paul, MN 55155",
    phone: "651-296-4193",
    email: "rep.patricia.mueller@house.mn.gov",
  },
  "09B": {
    title: "Rep. Tom Murphy",
    name: "Tom Murphy",
    district: "09B",
    party: "R",
    address: "313 State Office Building St. Paul, MN 55155",
    phone: "651-296-4946",
    email: "rep.tom.murphy@house.mn.gov",
  },
  "45A": {
    title: "Rep. Andrew Myers",
    name: "Andrew Myers",
    district: "45A",
    party: "R",
    address: "377 State Office Building St. Paul, MN 55155",
    phone: "651-296-9188",
    email: "rep.andrew.myers@house.mn.gov",
  },
  "34A": {
    title: "Rep. Danny Nadeau",
    name: "Danny Nadeau",
    district: "34A",
    party: "R",
    address: "291 State Office Building St. Paul, MN 55155",
    phone: "651-296-4315",
    email: "rep.danny.nadeau@house.mn.gov",
  },
  "48A": {
    title: "Rep. Jim Nash",
    name: "Jim Nash",
    district: "48A",
    party: "R",
    address: "349 State Office Building St. Paul, MN 55155",
    phone: "651-296-4282",
    email: "rep.jim.nash@house.mn.gov",
  },
  "38A": {
    title: "Rep. Michael Nelson",
    name: "Michael Nelson",
    district: "38A",
    party: "DFL",
    address: "585 State Office Building St. Paul, MN 55155",
    phone: "651-296-3751",
    email: "rep.michael.nelson@house.mn.gov",
  },
  "11B": {
    title: "Rep. Nathan Nelson",
    name: "Nathan Nelson",
    district: "11B",
    party: "R",
    address: "393 State Office Building St. Paul, MN 55155",
    phone: "651-296-0518",
    email: "rep.nathan.nelson@house.mn.gov",
  },
  "28B": {
    title: "Rep. Anne Neu Brindley",
    name: "Anne Neu Brindley",
    district: "28B",
    party: "R",
    address: "251 State Office Building St. Paul, MN 55155",
    phone: "651-296-5377",
    email: "rep.anne.neu@house.mn.gov",
  },
  "35B": {
    title: "Rep. Jerry Newton",
    name: "Jerry Newton",
    district: "35B",
    party: "DFL",
    address: "367 State Office Building St. Paul, MN 55155",
    phone: "651-296-1729",
    email: "rep.jerry.newton@house.mn.gov",
  },
  "31A": {
    title: "Rep. Harry Niska",
    name: "Harry Niska",
    district: "31A",
    party: "R",
    address: "337 State Office Building St. Paul, MN 55155",
    phone: "651-296-2439",
    email: "rep.harry.niska@house.mn.gov",
  },
  "60B": {
    title: "Rep. Mohamud Noor",
    name: "Mohamud Noor",
    district: "60B",
    party: "DFL",
    address: "379 State Office Building St. Paul, MN 55155",
    phone: "651-296-4257",
    email: "rep.mohamud.noor@house.mn.gov",
  },
  "32B": {
    title: "Rep. Matt Norris",
    name: "Matt Norris",
    district: "32B",
    party: "DFL",
    address: "507 State Office Building St. Paul, MN 55155",
    phone: "651-296-2907",
    email: "rep.matt.norris@house.mn.gov",
  },
  "30B": {
    title: "Rep. Paul Novotny",
    name: "Paul Novotny",
    district: "30B",
    party: "R",
    address: "301 State Office Building St. Paul, MN 55155",
    phone: "651-296-4237",
    email: "rep.paul.novotny@house.mn.gov",
  },
  "13B": {
    title: "Rep. Tim O'Driscoll",
    name: "Tim O'Driscoll",
    district: "13B",
    party: "R",
    address: "237 State Office Building St. Paul, MN 55155",
    phone: "651-296-7808",
    email: "rep.tim.odriscoll@house.mn.gov",
  },
  "22A": {
    title: "Rep. Bjorn Olson",
    name: "Bjorn Olson",
    district: "22A",
    party: "R",
    address: "229 State Office Building St. Paul, MN 55155",
    phone: "651-296-3240",
    email: "rep.bjorn.olson@house.mn.gov",
  },
  "08A": {
    title: "Rep. Liz Olson",
    name: "Liz Olson",
    district: "08A",
    party: "DFL",
    address: "479 State Office Building St. Paul, MN 55155",
    phone: "651-296-4246",
    email: "rep.liz.olson@house.mn.gov",
  },
  "26A": {
    title: "Rep. Gene Pelowski, Jr.",
    name: "Gene Pelowski Jr.",
    district: "26A",
    party: "DFL",
    address: "491 State Office Building St. Paul, MN 55155",
    phone: "651-296-8637",
    email: "rep.gene.pelowski@house.mn.gov",
  },
  "65B": {
    title: "Rep. María Isa Pérez-Vega",
    name: "María Isa Pérez-Vega",
    district: "65B",
    party: "DFL",
    address: "583 State Office Building St. Paul, MN 55155",
    phone: "651-296-9714",
    email: "rep.maria.isa.perez-vega@house.mn.gov",
  },
  "14A": {
    title: "Rep. Bernie Perryman",
    name: "Bernie Perryman",
    district: "14A",
    party: "R",
    address: "321 State Office Building St. Paul, MN 55155",
    phone: "651-296-6316",
    email: "rep.bernie.perryman@house.mn.gov",
  },
  "19B": {
    title: "Rep. John Petersburg",
    name: "John Petersburg",
    district: "19B",
    party: "R",
    address: "217 State Office Building St. Paul, MN 55155",
    phone: "651-296-5368",
    email: "rep.john.petersburg@house.mn.gov",
  },
  "22B": {
    title: "Rep. Brian Pfarr",
    name: "Brian Pfarr",
    district: "22B",
    party: "R",
    address: "351 State Office Building St. Paul, MN 55155",
    phone: "651-296-7065",
    email: "rep.brian.pfarr@house.mn.gov",
  },
  "64B": {
    title: "Rep. Dave Pinto",
    name: "Dave Pinto",
    district: "64B",
    party: "DFL",
    address: "503 State Office Building St. Paul, MN 55155",
    phone: "651-296-4199",
    email: "rep.dave.pinto@house.mn.gov",
  },
  "49A": {
    title: "Rep. Laurie Pryor",
    name: "Laurie Pryor",
    district: "49A",
    party: "DFL",
    address: "571 State Office Building St. Paul, MN 55155",
    phone: "651-296-3964",
    email: "rep.laurie.pryor@house.mn.gov",
  },
  "58A": {
    title: "Rep. Kristi Pursell",
    name: "Kristi Pursell",
    district: "58A",
    party: "DFL",
    address: "523 State Office Building St. Paul, MN 55155",
    phone: "651-296-0171",
    email: "rep.kristi.pursell@house.mn.gov",
  },
  "24A": {
    title: "Rep. Duane Quam",
    name: "Duane Quam",
    district: "24A",
    party: "R",
    address: "247 State Office Building St. Paul, MN 55155",
    phone: "651-296-9236",
    email: "rep.duane.quam@house.mn.gov",
  },
  "29B": {
    title: "Rep. Marion Rarick",
    name: "Marion Rarick",
    district: "29B",
    party: "R",
    address: "201 State Office Building St. Paul, MN 55155",
    phone: "651-296-5063",
    email: "rep.marion.rarick@house.mn.gov",
  },
  "48B": {
    title: "Rep. Lucy Rehm",
    name: "Lucy Rehm",
    district: "48B",
    party: "DFL",
    address: "533 State Office Building St. Paul, MN 55155",
    phone: "651-296-5066",
    email: "rep.lucy.rehm@house.mn.gov",
  },
  "52A": {
    title: "Rep. Liz Reyer",
    name: "Liz Reyer",
    district: "52A",
    party: "DFL",
    address: "575 State Office Building St. Paul, MN 55155",
    phone: "651-296-4128",
    email: "rep.liz.reyer@house.mn.gov",
  },
  "37A": {
    title: "Rep. Kristin Robbins",
    name: "Kristin Robbins",
    district: "37A",
    party: "R",
    address: "239 State Office Building St. Paul, MN 55155",
    phone: "651-296-7806",
    email: "rep.kristin.robbins@house.mn.gov",
  },
  "21A": {
    title: "Rep. Joe Schomacker",
    name: "Joe Schomacker",
    district: "21A",
    party: "R",
    address: "209 State Office Building St. Paul, MN 55155",
    phone: "651-296-5505",
    email: "rep.joe.schomacker@house.mn.gov",
  },
  "10B": {
    title: "Rep. Isaac Schultz",
    name: "Isaac Schultz",
    district: "10B",
    party: "R",
    address: "273 State Office Building St. Paul, MN 55155",
    phone: "651-296-6746",
    email: "rep.isaac.schultz@house.mn.gov",
  },
  "31B": {
    title: "Rep. Peggy Scott",
    name: "Peggy Scott",
    district: "31B",
    party: "R",
    address: "335 State Office Building St. Paul, MN 55155",
    phone: "651-296-4231",
    email: "rep.peggy.scott@house.mn.gov",
  },
  "63A": {
    title: "Rep. Samantha Sencer-Mura",
    name: "Samantha Sencer-Mura",
    district: "63A",
    party: "DFL",
    address: "417 State Office Building St. Paul, MN 55155",
    phone: "651-296-0173",
    email: "rep.samantha.sencer-mura@house.mn.gov",
  },
  "03A": {
    title: "Rep. Roger Skraba",
    name: "Roger Skraba",
    district: "03A",
    party: "R",
    address: "221 State Office Building St. Paul, MN 55155",
    phone: "651-296-2190",
    email: "rep.roger.skraba@house.mn.gov",
  },
  "25B": {
    title: "Rep. Andy Smith",
    name: "Andy Smith",
    district: "25B",
    party: "DFL",
    address: "411 State Office Building St. Paul, MN 55155",
    phone: "651-296-9249",
    email: "rep.andy.smith@house.mn.gov",
  },
  "35A": {
    title: "Rep. Zack Stephenson",
    name: "Zack Stephenson",
    district: "35A",
    party: "DFL",
    address: "449 State Office Building St. Paul, MN 55155",
    phone: "651-296-5513",
    email: "rep.zack.stephenson@house.mn.gov",
  },
  "15A": {
    title: "Rep. Chris Swedzinski",
    name: "Chris Swedzinski",
    district: "15A",
    party: "R",
    address: "245 State Office Building St. Paul, MN 55155",
    phone: "651-296-5374",
    email: "rep.chris.swedzinski@house.mn.gov",
  },
  "54A": {
    title: "Rep. Brad Tabke",
    name: "Brad Tabke",
    district: "54A",
    party: "DFL",
    address: "543 State Office Building St. Paul, MN 55155",
    phone: "651-296-8872",
    email: "rep.brad.tabke@house.mn.gov",
  },
  "15B": {
    title: "Rep. Paul Torkelson",
    name: "Paul Torkelson",
    district: "15B",
    party: "R",
    address: "261 State Office Building St. Paul, MN 55155",
    phone: "651-296-9303",
    email: "rep.paul.torkelson@house.mn.gov",
  },
  "16A": {
    title: "Rep. Dean Urdahl",
    name: "Dean Urdahl",
    district: "16A",
    party: "R",
    address: "279 State Office Building St. Paul, MN 55155",
    phone: "651-296-4344",
    email: "rep.dean.urdahl@house.mn.gov",
  },
  "38B": {
    title: "Rep. Samantha Vang",
    name: "Samantha Vang",
    district: "38B",
    party: "DFL",
    address: "545 State Office Building St. Paul, MN 55155",
    phone: "651-296-3709",
    email: "rep.samantha.vang@house.mn.gov",
  },
  "52B": {
    title: "Rep. Bianca Virnig",
    name: "Bianca Virnig",
    district: "52B",
    party: "DFL",
    address: "403 State Office Building St. Paul, MN 55155",
    phone: "651-296-4192",
    email: "rep.bianca.virnig@house.mn.gov",
  },
  "32A": {
    title: "Rep. Nolan West",
    name: "Nolan West",
    district: "32A",
    party: "R",
    address: "287 State Office Building St. Paul, MN 55155",
    phone: "651-296-4226",
    email: "rep.nolan.west@house.mn.gov",
  },
  "05B": {
    title: "Rep. Mike Wiener",
    name: "Mike Wiener",
    district: "05B",
    party: "R",
    address: "327 State Office Building St. Paul, MN 55155",
    phone: "651-296-4293",
    email: "rep.mike.wiener@house.mn.gov",
  },
  "41A": {
    title: "Rep. Mark Wiens",
    name: "Mark Wiens",
    district: "41A",
    party: "R",
    address: "353 State Office Building St. Paul, MN 55155",
    phone: "651-296-4244",
    email: "rep.mark.wiens@house.mn.gov",
  },
  "57B": {
    title: "Rep. Jeff Witte",
    name: "Jeff Witte",
    district: "57B",
    party: "R",
    address: "255 State Office Building St. Paul, MN 55155",
    phone: "651-296-4240",
    email: "rep.jeff.witte@house.mn.gov",
  },
  "14B": {
    title: "Rep. Dan Wolgamott",
    name: "Dan Wolgamott",
    district: "14B",
    party: "DFL",
    address: "401 State Office Building St. Paul, MN 55155",
    phone: "651-296-6612",
    email: "rep.dan.wolgamott@house.mn.gov",
  },
  "67B": {
    title: "Rep. Jay Xiong",
    name: "Jay Xiong",
    district: "67B",
    party: "DFL",
    address: "557 State Office Building St. Paul, MN 55155",
    phone: "651-296-4201",
    email: "rep.jay.xiong@house.mn.gov",
  },
  "46B": {
    title: "Rep. Cheryl Youakim",
    name: "Cheryl Youakim",
    district: "46B",
    party: "DFL",
    address: "443 State Office Building St. Paul, MN 55155",
    phone: "651-296-9889",
    email: "rep.cheryl.youakim@house.mn.gov",
  },
  "03B": {
    title: "Rep. Natalie Zeleznikar",
    name: "Natalie Zeleznikar",
    district: "03B",
    party: "R",
    address: "223 State Office Building St. Paul, MN 55155",
    phone: "651-296-2676",
    email: "rep.natalie.zeleznikar@house.mn.gov",
  }
}

export const stateSenate = [
  {
    title: "Sen. Abeler",
    name: "Jim Abeler",
    party: "R",
    address: "2207 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-3733",
    email: "sen.jim.abeler@senate.mn",
  },
  {
    title: "Sen. Anderson",
    name: "Bruce D. Anderson",
    party: "R",
    address: "2209 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5981",
    email: "sen.bruce.anderson@senate.mn",
  },
  {
    title: "Sen. Bahr",
    name: "Calvin K. Bahr",
    party: "R",
    address: "2415 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-3219",
    email: ""
  },
  {
    title: "Assistant Majority Leader Sen. Boldon",
    name: "Liz Boldon",
    party: "DFL",
    address: "3201 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-3903",
    email: ""
  },
  {
    title: "Sen. Carlson",
    name: "Jim Carlson",
    party: "DFL",
    address: "3221 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-297-8073",
    email: ""
  },
  {
    title: "President of the Senate Sen. Champion",
    name: "Bobby Joe Champion",
    party: "DFL",
    address: "3401 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-9246",
    email: "sen.bobby.champion@senate.mn",
  },
  {
    title: "Assistant Minority Leader Sen. Coleman",
    name: "Julia E. Coleman",
    party: "R",
    address: "2303 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4837",
    email: "sen.julia.coleman@senate.mn",
  },
  {
    title: "Sen. Cwodzinski",
    name: "Steve A. Cwodzinski",
    party: "DFL",
    address: "3207 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-1314",
    email: ""
  },
  {
    title: "Sen. Dahms",
    name: "Gary H. Dahms",
    party: "R",
    address: "2219 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-8138",
    email: "sen.gary.dahms@senate.mn",
  },
  {
    title: "Sen. Dibble",
    name: "D. Scott Dibble",
    party: "DFL",
    address: "3107 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4191",
    email: ""
  },
  {
    title: "Sen. Dornink",
    name: "Gene Dornink",
    party: "R",
    address: "3411 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5240",
    email: "sen.gene.dornink@senate.mn",
  },
  {
    title: "Sen. Draheim",
    name: "Rich Draheim",
    party: "R",
    address: "2225 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5558",
    email: "sen.rich.draheim@senate.mn",
  },
  {
    title: "Sen. Drazkowski",
    name: "Steve Drazkowski",
    party: "R",
    address: "2411 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5612",
    email: ""
  },
  {
    title: "Assistant Minority Leader Sen. Duckworth",
    name: "Zach Duckworth",
    party: "R",
    address: "2229 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-7633",
    email: ""
  },
  {
    title: "Sen. Dziedzic",
    name: "Kari Dziedzic",
    party: "DFL",
    address: "3113 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-7809",
    email: ""
  },
  {
    title: "Assistant Minority Leader Sen. Eichorn",
    name: "Justin D. Eichorn",
    party: "R",
    address: "2235 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-7079",
    email: ""
  },
  {
    title: "Sen. Farnsworth",
    name: "Robert D. Farnsworth",
    party: "R",
    address: "2323 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-8436",
    email: ""
  },
  {
    title: "Sen. Fateh",
    name: "Omar Fateh",
    party: "DFL",
    address: "3219 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4261",
    email: ""
  },
  {
    title: "Assistant Majority Leader Sen. Frentz",
    name: "Nick A. Frentz",
    party: "DFL",
    address: "3109 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-6153",
    email: ""
  },
  {
    title: "Sen. Green",
    name: "Steve Green",
    party: "R",
    address: "2319 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-297-8063",
    email: "sen.steve.green@senate.mn",
  },
  {
    title: "Sen. Gruenhagen",
    name: "Glenn H. Gruenhagen",
    party: "R",
    address: "2417 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4131",
    email: "sen.glenn.gruenhagen@senate.mn",
  },
  {
    title: "Sen. Gustafson",
    name: "Heather Gustafson",
    party: "DFL",
    address: "3103 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-1253",
    email: ""
  },
  {
    title: "Sen. Hauschild",
    name: "Grant Hauschild",
    party: "DFL",
    address: "3111 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-1789",
    email: ""
  },
  {
    title: "Assistant Majority Leader Sen. Hawj",
    name: "Foung Hawj",
    party: "DFL",
    address: "3231 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5285",
    email: ""
  },
  {
    title: "Sen. Hoffman",
    name: "John A. Hoffman",
    party: "DFL",
    address: "2111 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4154",
    email: ""
  },
  {
    title: "Assistant Minority Leader Sen. Housley",
    name: "Karin Housley",
    party: "R",
    address: "2213 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4351",
    email: ""
  },
  {
    title: "Sen. Howe",
    name: "Jeff R. Howe",
    party: "R",
    address: "2231 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-2084",
    email: ""
  },
  {
    title: "Assistant Minority Leader Sen. Jasinski",
    name: "John R. Jasinski",
    party: "R",
    address: "2227 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-0284",
    email: ""
  },
  {
    title: "Minority Leader Sen. Johnson",
    name: "Mark T. Johnson",
    party: "R",
    address: "2401 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5782",
    email: ""
  },
  {
    title: "Sen. Klein",
    name: "Matt D. Klein",
    party: "DFL",
    address: "2105 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4370",
    email: ""
  },
  {
    title: "Sen. Koran",
    name: "Mark W. Koran",
    party: "R",
    address: "2203 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5419",
    email: ""
  },
  {
    title: "Sen. Kreun",
    name: "Michael E. Kreun",
    party: "R",
    address: "2321 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-1282",
    email: ""
  },
  {
    title: "Assistant Majority Leader Sen. Kunesh",
    name: "Mary K. Kunesh",
    party: "DFL",
    address: "3209 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4334",
    email: ""
  },
  {
    title: "Sen. Kupec",
    name: "Robert J. Kupec",
    party: "DFL",
    address: "3101 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-3205",
    email: ""
  },
  {
    title: "Sen. Lang",
    name: "Andrew R. Lang",
    party: "R",
    address: "2205 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4918",
    email: ""
  },
  {
    title: "Sen. Latz",
    name: "Ron Latz",
    party: "DFL",
    address: "3105 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-297-8065",
    email: ""
  },
  {
    title: "Sen. Lieske",
    name: "Bill Lieske",
    party: "R",
    address: "2327 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5019",
    email: "sen.bill.lieske@senate.mn",
  },
  {
    title: "Sen. Limmer",
    name: "Warren Limmer",
    party: "R",
    address: "2221 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-2159",
    email: ""
  },
  {
    title: "Sen. Lucero",
    name: "Eric Lucero",
    party: "R",
    address: "2413 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5655",
    email: ""
  },
  {
    title: "Sen. Mann",
    name: "Alice Mann",
    party: "DFL",
    address: "3225 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-6238",
    email: ""
  },
  {
    title: "Sen. Marty",
    name: "John Marty",
    party: "DFL",
    address: "3235 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5645",
    email: ""
  },
  {
    title: "Sen. Mathews",
    name: "Andrew Mathews",
    party: "R",
    address: "2233 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-8075",
    email: ""
  },
  {
    title: "Sen. Maye Quade",
    name: "Erin K. Maye Quade",
    party: "DFL",
    address: "3227 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4120",
    email: ""
  },
  {
    title: "Sen. McEwen",
    name: "Jennifer A. McEwen",
    party: "DFL",
    address: "3217 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4188",
    email: ""
  },
  {
    title: "Sen. Miller",
    name: "Jeremy R. Miller",
    party: "R",
    address: "2215 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5649",
    email: "sen.jeremy.miller@senate.mn",
  },
  {
    title: "Sen. Mitchell",
    name: "Nicole Mitchell",
    party: "DFL",
    address: "3229 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5537",
    email: ""
  },
  {
    title: "Sen. Mohamed",
    name: "Zaynab Mohamed",
    party: "DFL",
    address: "2103 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4274",
    email: ""
  },

  {
    title: "Assistant Majority Leader Sen. Morrison",
    name: "Kelly L. Morrison",
    party: "DFL",
    address: "3205 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-9261",
    email: ""
  },

  {
    title: "Majority Leader Sen. Murphy",
    name: "Erin P. Murphy",
    party: "DFL",
    address: "3211 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5931",
    email: ""
  },
  {
    title: "Sen. Nelson",
    name: "Carla J. Nelson",
    party: "R",
    address: "2301 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4848",
    email: "sen.carla.nelson@senate.mn",
  },

  {
    title: "Assistant Majority Leader Sen. Oumou Verbeten",
    name: "Clare Oumou Verbeten",
    party: "DFL",
    address: "2101 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-8866",
    email: ""
  },
  {
    title: "Sen. Pappas",
    name: "Sandra L. Pappas",
    party: "DFL",
    address: "2113 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-1802",
    email: ""
  },
  {
    title: "Sen. Pha",
    name: "Susan Pha",
    party: "DFL",
    address: "3233 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-2556",
    email: ""
  },
  {
    title: "Sen. Port",
    name: "Lindsey Port",
    party: "DFL",
    address: "3213 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5975",
    email: ""
  },
  {
    title: "Sen. Pratt",
    name: "Eric R. Pratt",
    party: "R",
    address: "2217 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4123",
    email: "sen.eric.pratt@senate.mn",
  },
  {
    title: "Sen. Putnam",
    name: "Aric Putnam",
    party: "DFL",
    address: "3215 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-6455",
    email: ""
  },
  {
    title: "Sen. Rarick",
    name: "Jason Rarick",
    party: "R",
    address: "3413 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-1508",
    email: "sen.jason.rarick@senate.mn",
  },
  {
    title: "Sen. Rasmusson",
    name: "Jordan Rasmusson",
    party: "R",
    address: "2409 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4875",
    email: ""
  },

  {
    title: "President Pro Tem Sen. Rest",
    name: "Ann H. Rest",
    party: "DFL",
    address: "328 Capitol St. Paul, MN 55155-1606",
    phone: "651-296-2889",
    email: ""
  },
  {
    title: "Sen. Seeberger",
    name: "Judy Seeberger",
    party: "DFL",
    address: "2109 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-297-8060",
    email: ""
  },
  {
    title: "Sen. Utke",
    name: "Paul J. Utke",
    party: "R",
    address: "2403 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-9651",
    email: "sen.paul.utke@senate.mn",
  },

  {
    title: "Assistant Minority Leader Sen. Weber",
    name: "Bill Weber",
    party: "R",
    address: "2211 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-5650",
    email: ""
  },
  {
    title: "Sen. Wesenberg",
    name: "Nathan Wesenberg",
    party: "R",
    address: "2325 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-4913",
    email: "sen.nathan.wesenberg@senate.mn",
  },
  {
    title: "Sen. Westlin",
    name: "Bonnie S. Westlin",
    party: "DFL",
    address: "3403 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-8869",
    email: ""
  },
  {
    title: "Sen. Westrom",
    name: "Torrey N. Westrom",
    party: "R",
    address: "2201 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-3826",
    email: "sen.torrey.westrom@senate.mn",
  },
  {
    title: "Sen. Wiklund",
    name: "Melissa H. Wiklund",
    party: "DFL",
    address: "2107 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-297-8061",
    email: ""
  },
  {
    title: "Sen. Xiong",
    name: "Tou Xiong",
    party: "DFL",
    address: "3203 Minnesota Senate Bldg. St. Paul, MN 55155",
    phone: "651-296-6820",
    email: ""
  }
]